version: '2.1'
services:
  phets-api:
    container_name: phets-api
    build: .
    environment:
      PORT: '4000'
      SHOW_URLS: 'true'
      EVENT_URL: '172.17.0.1' # for mac or windows use host.docker.internal instead
      EVENT_PORT: '4001'
      EVENT_ENTRY: 'event'
    ports:
      - '4000:4000'
