version: "2.1"
services:
    phets-api:
        container_name: phets-api
        build: .
        environment:
            PORT: "4000"
            SHOW_URLS: "true"
            EVENT_URL: "172.17.0.1" # for mac or windows use host.docker.internal instead
            EVENT_PORT: "4001"
            EVENT_ENTRY: "event"
            CHAT_URL: "172.17.0.1" # for mac or windows use host.docker.internal instead
            CHAT_PORT: "4002"
            ANIMAL_URL: "172.17.0.1" # for mac or windows use host.docker.internal instead
            ANIMAL_PORT: "4003"
            INTERACTION_URL: "172.17.0.1" # for mac or windows use host.docker.internal instead
            INTERACTION_PORT: "4005"
            INTERACTION_ENTRY: "api/interaction"
            NOTIFICATION_URL: "172.17.0.1"
            NOTIFICATION_PORT: "4004"
            NOTIFICATION_ENTRY: "notifications"
            EMAIL_ENTRY: "emails"
            USER_URL: "172.17.0.1"
            USER_PORT: "4006"
        ports:
            - "4000:4000"
