version: "2.1"
services:
    phets-api:
        container_name: phets-api
        build: .
        environment:
            PORT: "4000"
            SHOW_URLS: "true"
            EVENT_URL: "172.17.0.1" # for mac or windows use host.docker.internal instead
            EVENT_PORT: "4001"
            EVENT_ENTRY: "event"
            ANIMAL_URL: "172.17.0.1" # for mac or windows use host.docker.internal instead
            ANIMAL_PORT: "4003"
            INTERACTION_URL: "172.17.0.1" # for mac or windows use host.docker.internal instead
            INTERACTION_PORT: "4005"
            INTERACTION_ENTRY: "api/interaction"
        ports:
            - "4000:4000"
